apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daisei-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JaisinhBhosale9712/argo-test.git'
    targetRevision: main
    path: helm-chart
    helm:
      values: |
        image:
          repository: jaybhosale9712/flask1
          tag: "v3"  # Updated image tag in ArgoCD YAML
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
