apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd  # The namespace where Argo CD is installed
spec:
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server
    namespace: monitoring  # The namespace where Prometheus will be deployed (create this namespace if not exists)
  project: default  # Argo CD project (you can customize it)
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # The Helm chart repository URL
    chart: prometheus  # The name of the Helm chart
    targetRevision: "latest"  # You can specify the version of the chart (e.g., "latest" or a specific version)
    helm:
      createNamespace: true  # Automatically creates the monitoring namespace if it doesn't exist
      values: |
        # You can override default values here
        serverFiles:
          prometheus.yml:
            global:
              scrape_interval: 15s
              scrape_timeout: 10s
      # The following ensures CRDs are installed before the chart is applied
      crds:
        install: true  # Install CRDs automatically with the Helm chart
    # Optionally, if you have custom values.yaml, you can reference it here.
    # If you want to point to your custom values.yaml, replace with:
    # helm:
    #   valueFiles:
    #     - path/to/custom-values.yaml
  syncPolicy:
    automated:
      prune: true  # This will ensure that any deleted resources are cleaned up
      selfHeal: true  # This will auto-heal the application if it's out of sync
